{% set version = "0.7" %}

package:
  name: dataclasses
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dataclasses/dataclasses-{{ version }}.tar.gz
  sha256: 494a6dcae3b8bcf80848eea2ef64c0cc5cd307ffc263e17cdf42f3e5420808e6

build:
  number: 0
  skip: true  # [py==27]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .  # [py==36]
  script: {{ PYTHON }} --version                                      # [py!=36]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dataclasses

about:
  home: https://github.com/ericvsmith/dataclasses
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'An implementation of PEP 557: Data Classes'

extra:
  recipe-maintainers:
    - ocefpaf
