{% set version = "0.7" %}

package:
  name: dataclasses
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dataclasses/dataclasses-{{ version }}.tar.gz
  sha256: 494a6dcae3b8bcf80848eea2ef64c0cc5cd307ffc263e17cdf42f3e5420808e6

build:
  number: 1
  noarch: python

outputs:
  - name: dataclasses
    version: "1!{{ version }}"
    script: noop.sh
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
    test:
      imports:
        - dataclasses

  - name: dataclasses
    version: "{{ version }}"
    script: build_python.sh
    requirements:
      host:
        - python =3.6
        - pip
      run:
        - python =3.6
    test:
      imports:
        - dataclasses

about:
  home: https://github.com/ericvsmith/dataclasses
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'An implementation of PEP 557: Data Classes'

extra:
  recipe-maintainers:
    - ocefpaf
