{% set version = "0.7" %}
{% set build_number = 1 %}

package:
  name: dataclasses
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dataclasses/dataclasses-{{ version }}.tar.gz
  sha256: 494a6dcae3b8bcf80848eea2ef64c0cc5cd307ffc263e17cdf42f3e5420808e6

build:
  {% if build_script == 'noop' %}
  number: {{ int(build_number) * 2 + 1 }}
  script: ./noop.sh
  {% else %}
  number: {{ int(build_number) * 2 }}
  script: ./build_pip.sh
  {% endif %}
  noarch: python

requirements:
  host:
    {% if build_script == 'noop' %}
    - python >=3.7
    {% else %}
    - python >=3.6,<3.7
    {% endif %}
    - pip
  run:
    {% if build_script == 'noop' %}
    - python >=3.7
    {% else %}
    - python >=3.6,<3.7
    {% endif %}


test:
  imports:
    - dataclasses

about:
  home: https://github.com/ericvsmith/dataclasses
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'An implementation of PEP 557: Data Classes'

extra:
  recipe-maintainers:
    - ocefpaf
