travis:
  secure:
    BINSTAR_TOKEN: OxGadKXW1DTwnx3QNYZQ3MiyJhd9LtRXtd1FB+uXHIuEho0EBZtKTSx7wycv1rVF6qRv/ogx+LR+dDvsxjLfWVP2xy5Mom9TWs80lkTMCCFdKYhNRSLDZfZl/eHYHz5S9nauSnOWAyYyS6Su9WJ8S++VvefnpMdc7iPQvazmj5qhStriwbgSUhm1IunXekTjxJKsrvAEe+o0eA6kxkTGlBwwmBmkRHmnTqY8E+ew/GgzyomvDaYD43ri+sHZXK/Ad2KwowakEkhI7aeU4QZJNpY6hPd+i9XlfknLZhYgYCAdmorbs8ZO+U3LLk+m8rVkO75yQZxIyACYe9OZSYBJ6GuY6PG1HHMThIjgTYIYLGjKpDrmB1OzCYIMhl0TLZpFfIt94D3APsY1RLMrQiAxWLctM/ThYu5j+3lg7gHnJYmB46iP0KjbMpzDYv1xCEB+PvDxwjmD5qZFH43/reeDURB3Jn//hSu++J2Jo9i2M8XSvgz8Gpqe4KqbWNOEfs6XetEU/QFGuM4g7cb3tw+NtYIJx7TrVs05AnReR0f/1zM7opqS7KhZykvxB+ZWMeJ85JfC7TszXD/FsSb61Q48cas4moYVRByJeyey1BsskRQH18wlOhuNgZXI5RgUL5kVuJuPdwJDC4Mt1mcXQPLzXO++9JDRcWv0ZTgDRBZq+TY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
