travis:
  secure:
    BINSTAR_TOKEN: GO6e1MMctcFpNOc5W8r7QKh7KAfDnVldMrt0/aNok3Fu7LJ3rjD6+eVxgoHdAkuhx9vePohJcwats1hw7Vh3Axrt98gB5NAPaGUH4jYMYrMjsWJ3QFZk10zSxtBpQDrCW26lEC+D2ca3x7ZaYRrI/UhNtmE7qgY1GdyZBBTyVLsNjZ2+ORpqY1HJgItavDnsftPpOdIzKpst7VOtIO2EJnPtJljGBSxJZEMbdpiEP0CiAdI9JOhFpWltUdYqkBgZtttwJvw2GHVgbqQ4F8uzajt/j+bIP3ylBg3+L+alFof+DkvxKXK2f1tiulzjGd/94xoWmlFD0ycbCxKVzVPKH7gBF/WJx23n0qoF6qPXg2M8hcPvZaEnt0/uM+leczwSw6ztOhHqS+QP6LfdAGFor427g/kfjJUx5BpsQKDRjAuwzxQmPoUnJrTu9CgK1dqMjCMkBY+kTY0Q90TkX3QD8vr1woDp2McXRFeA0omiy6wsiZ0N2eINCSkvbOG27ivR+tskWoQEH0cWLUexItpZm7+LV8v469t2sVrjgaFStXqtIjxxTO2zAu+J0Hjg2bVsiNqlbyfVZbz/nvHaHg/ahcZUKGMfOa3HxxcbRP38LLY2n1gqBdeHGOcCvLsAzQ9Vql+kOUhh2bCb3XaFE75vsu+N6/TcAjju9ilX9X9QJlI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
